import fs from "fs";
import path from "path";

const dictPath = path.resolve("src/lib/i18n/dictionaries.ts");
let content = fs.readFileSync(dictPath, "utf-8");

const enAdditions = `
  nav: {
    about: "About Us",
    fellowship: "The Fellowship",
    report: "Daily Report"
  },
  header: {
    title: "Swavalambi Bharat Yuva",
    titleMobile: "SBYF",
    toggleLang: "हिंदी",
    province: "Chhattisgarh Province",
    registerBtn: "Register Now",
    updates: "Updates",
    marquee: "Join the Movement: Swavalambi Bharat Yuva Fellowship Registration for Batch 2026 is currently active. [Contact: 9685322910]"
  },
  footer: {
    title: "Swavalambi Bharat Abhiyan",
    province: "Chhattisgarh Province",
    desc: "Our goal is to provide employment to every citizen by 2030 and make India self-reliant. [cite: 184]",
    linksTitle: "Important Links",
    aboutMySba: "About MySBA",
    fellowshipDetails: "Fellowship Details",
    successStories: "Success Stories",
    resourceMapping: "Resource Mapping",
    jskCenters: "JSK Centers",
    resourcesTitle: "Resources",
    msmeSchemes: "MSME Schemes",
    startupIndia: "Startup India",
    skillIndia: "Skill India",
    mudraLoan: "Mudra Loan Info",
    regGuide: "Registration Guide",
    contactTitle: "Contact Us",
    callWhatsapp: "Call/WhatsApp",
    emailAddr: "Email Address",
    location: "Location",
    rights: "Swavalambi Bharat Abhiyaan (SBA) - All Rights Reserved",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    sitemap: "Sitemap",
    atmanirbhar: "Atmanirbhar Bharat"
  },
  homeNew: {
    badge: "Swavalambi Bharat Abhiyan (SBA)",
    titlePart1: "Swavalambi Bharat",
    titlePart2: "Yuva Fellowship",
    subtitle: "This is not a job, but a 6-month youth fellowship to learn nation-building and entrepreneurship. [cite: 181]",
    durationLabel: "Duration",
    durationVal: "6 Months [cite: 41]",
    natureLabel: "Nature",
    natureVal: "Part-Time [cite: 28]",
    engageLabel: "Engagement",
    engageVal: "6-8 Hours/Week [cite: 45]",
    registerBtn: "REGISTER NOW",
    downloadBtn: "DOWNLOAD PROPOSAL",
    visionTitle: "Our Vision 2030 [cite: 5]",
    vision1: "Mindset change regarding entrepreneurship [cite: 178]",
    vision2: "Localized employment opportunities [cite: 18]",
    vision3: "Resource mapping in Rural Areas [cite: 60]",
    vision4: "Simplified awareness of MSME schemes [cite: 62]",
    rolesTitle: "Roles & Measurable Outputs [cite: 81]",
    rolesSubtitle: "Every Fellow is assigned a clear vertical with specific monthly deliverables.",
    rolesAnalysis: "Vertical Analysis: 06 Key Areas",
    role1T: "Local Mapping", role1D: "Identification of traditional skills and regional business potential[cite: 95].",
    role2T: "Success Stories", role2D: "Documenting stories of local entrepreneurs and startups[cite: 57].",
    role3T: "Scheme Analysis", role3D: "Simplified presentation of MSME, Startup, and Skill schemes[cite: 91].",
    role4T: "Social Media", role4D: "Managing platforms, posts, reels, and event campaigns[cite: 84].",
    role5T: "Innovation Outreach", role5D: "Identifying ideas and startups within college campuses[cite: 87].",
    role6T: "Field Coordination", role6D: "Coordinating with institutions, traders, and students[cite: 93].",
    hybridTitlePart1: "Hybrid Fellowship",
    hybridTitlePart2: "Model Structure [cite: 118]",
    hybridDesc: "Designed for low-budget high-commitment impact, focusing on volunteerism and core leadership.",
    volFellows: "Volunteer Fellows (80%) [cite: 120]",
    volDesc: "Focus on learning outcomes, field exposure, and recognition without stipend[cite: 129, 130].",
    coreFellows: "Core Fellows (20%) [cite: 124]",
    coreDesc: "Selected based on 2-month performance. Eligible for travel allowance (₹2000-₹5000)[cite: 131].",
    coreCriteria: "Core Fellow Selection Criteria [cite: 133]",
    coreC1: "Regular attendance and punctuality [cite: 144]",
    coreC2: "Quality of research and documentation [cite: 145]",
    coreC3: "Timely submission of assigned tasks [cite: 148]",
    coreC4: "Initiative and leadership skills [cite: 147]",
    planTitle: "Detailed Work Plan (Step-by-Step) [cite: 96]",
    planSubtitle: "Monthly Output-Based Reporting",
    planM1: "Month 1 [cite: 100]", planT1: "Orientation & Training [cite: 106]", planD1: "Program induction and tool training.",
    planM2: "Month 2 [cite: 101]", planT2: "Local Mapping [cite: 109]", planD2: "Identifying regional business opportunities.",
    planM3: "Month 3 [cite: 102]", planT3: "Success Stories [cite: 110]", planD3: "Documentation of local entrepreneurs.",
    planM4: "Month 4 [cite: 103]", planT4: "Govt Scheme Research [cite: 111]", planD4: "Analysis of MSME & startup programs.",
    planM5: "Month 5 [cite: 104]", planT5: "Youth Outreach [cite: 113]", planD5: "Campus engagement and idea sourcing.",
    planM6: "Month 6 [cite: 105]", planT6: "Final Presentation [cite: 115]", planD6: "Report submission and state felicitation.",
    eligibilityTitle: "Eligibility Criteria [cite: 66]",
    e1: "Graduates / Post Graduates [cite: 68]",
    e2: "Current University Students [cite: 68]",
    e3: "Computer & Social Media Knowledge [cite: 69]",
    e4: "Interest in Nation Building [cite: 74]",
    e5: "NSS / NCC / E-Cell Background [cite: 75]",
    e6: "Field Work & Documentation Interest [cite: 76]",
    rewardsTitle: "Recognition & Rewards [cite: 156]",
    r1L: "Certification & LOR [cite: 163]", r1D: "State-level felicitation and recognition letters.",
    r2L: "Best Fellow of the Month [cite: 161]", r2D: "Monthly awards for top performance across verticals.",
    r3L: "Project Credit Support [cite: 165]", r3D: "Field work credits for university courses (NSS/NCC).",
    ctaTitle1: "Let's build a",
    ctaTitle2: "Self-Reliant Chhattisgarh, Self-Reliant India! [cite: 128]",
    ctaSubtitle: "Every Home Swadeshi, Every Youth Entrepreneur [cite: 128]",
    connectUs: "Connect with Us [cite: 182]",
    applyBtn: "APPLY FOR FELLOWSHIP",
    reportBtn: "REPORT PORTAL",
    jskBtn: "JSK KENDRA"
  },
  about: {
    badge: "Atmanirbhar Bharat 2030",
    titlePart1: "Our Goal:",
    titlePart2: "Self-Reliant and Capable India",
    desc: "Swavalambi Bharat Abhiyan (SBA) is a national initiative committed to providing employment and self-employment opportunities to every citizen of India by 2030.",
    f1T: "Mindset Change", f1D: "Transforming the mindset of youth from job seekers to job providers (entrepreneurs).",
    f2T: "Local Promotion", f2D: "Encouraging and coordinating employment-oriented enterprises and projects at the local level.",
    f3T: "Integrated Centers", f3D: "Establishment of Integrated Employment Centers (JSK) in every district for all related activities.",
    digiTitle1: "MySBA:",
    digiTitle2: "The Power of Digital Platform",
    digiDesc: "MySBA is the digital platform of Swavalambi Bharat Abhiyan, aimed at changing the mindset of youth and empowering them to bring positive change.",
    p1: "Bringing individuals, industries, and professionals onto a single platform.",
    p2: "A decentralized approach to empower youth at the local level.",
    p3: "Supporting the development of FPOs, SHGs, and other cooperative movements.",
    infraTitle: "Digital Infrastructure",
    infraPT1: "Physical Touchpoint",
    infraPT2: "Jila Swavalamban Kendra (JSK)",
    infraPT3: "A physical point where youth can get help and guidance in building their future.",
    infraES1: "Economic Support",
    infraES2: "Skill Documentation",
    infraES3: "Encouraging entrepreneurship by organizing skills established or underway at the grassroots level.",
    cgTitle: "Chhattisgarh Province: Boosting Local Economy",
    cgDesc: "To strengthen the local economy of Chhattisgarh, we are connecting youth with nation-building through self-employment, innovation, and entrepreneurship. [cite: 53, 64]",
    pgLabel: "Primary Goal", pgDesc: "Resource Mapping [cite: 60]",
    sgLabel: "Secondary Goal", sgDesc: "Documentation of Success Stories [cite: 56, 57]",
    joinBtn: "Join the Movement",
    contactTitle: "Contact Details (SBA Chhattisgarh)",
    whatsapp: "WhatsApp: 9685322910 [cite: 183]",
    email: "Email: sbachhattisgarh@gmail.com [cite: 183]",
    footer: "Atmanirbhar Chhattisgarh | Atmanirbhar Bharat"
  },
  fellowship: {
    badge: "Structured 6-Month Program",
    titlePart1: "Swavalambi Bharat",
    titlePart2: "Yuva Fellowship",
    desc: "A transformative initiative to bridge the gap between youth, local opportunities, and entrepreneurship guidance. This is not a job, but a mission for nation-building[cite: 18, 181].",
    hybridTitle1: "Hybrid Fellowship",
    hybridTitle2: "Model",
    hybridDesc: "Designed for maximum local impact with a focus on leadership and volunteerism[cite: 118, 119].",
    volTitle: "Volunteer Fellows (80%)",
    volDesc: "Focus on training, field exposure, and social impact[cite: 120, 129].",
    coreTitle: "Core Fellows (20%)",
    coreDesc: "Selected based on 2-month performance for leadership roles[cite: 124, 131].",
    c1T: "Time Commitment", c1V: "6-8 Hours/Week", c1D: "Flexible engagement for students and professionals[cite: 45].",
    c2T: "Performance Review", c2V: "At 2 Months", c2D: "Rigorous selection for Core Fellow track[cite: 134, 142].",
    c3T: "Financial Support", c3V: "₹2000 - ₹5000", c3D: "Support/travel allowance for selected Core Fellows[cite: 131].",
    c4T: "Recognition", c4V: "National Level", c4D: "Certificate, LOR, and Best Fellow awards[cite: 49, 163].",
    rolesTitle: "Roles & Measurable Outputs",
    role1T: "Resource Mapping", role1D: "Identification of traditional skills and business potential[cite: 94, 177].",
    role2T: "Success Stories", role2D: "Documenting stories of local entrepreneurs and businesses[cite: 56, 57].",
    role3T: "Scheme Analysis", role3D: "Simplified presentation of MSME and Startup schemes[cite: 90, 91].",
    role4T: "Social Media", role4D: "Platform management and content campaigns[cite: 82, 84].",
    role5T: "Innovation Outreach", role5D: "Identifying ideas and startups in colleges[cite: 86, 87].",
    role6T: "Field Coordination", role6D: "Coordination with institutions and entrepreneurs[cite: 92, 93].",
    roadmapTitle: "Implementation Roadmap",
    planM1: "Month 1", planT1: "Orientation & Training", planD1: "Induction into SBA tools and research methods[cite: 106, 108].",
    planM2: "Month 2", planT2: "Local Mapping", planD2: "Data collection of regional resources and businesses[cite: 107, 109].",
    planM3: "Month 3", planT3: "Success Stories", planD3: "Documentation and digital story creation[cite: 110].",
    planM4: "Month 4", planT4: "Scheme Research", planD4: "In-depth analysis of MSME and loan programs[cite: 111, 112].",
    planM5: "Month 5", planT5: "Campus Outreach", planD5: "Entrepreneurship awareness in colleges[cite: 113].",
    planM6: "Month 6", planT6: "Final Report", planD6: "Final presentation and impact submission[cite: 114, 115].",
    whoTitle: "Who Can Join?",
    e1: "Graduate / PG Students", e2: "Computer Knowledge", e3: "Interest in Nation Building", e4: "NSS / NCC / E-Cell Background",
    applyBtn: "Apply Now",
    batchText: "Batch 2026 Registration Open"
  }
`;

const hiAdditions = `
  nav: {
    about: "हमारे बारे में",
    fellowship: "फेलोशिप",
    report: "दैनिक रिपोर्ट"
  },
  header: {
    title: "स्वावलंबी भारत युवा",
    titleMobile: "SBYF",
    toggleLang: "ENG",
    province: "छत्तीसगढ़ प्रांत",
    registerBtn: "अभी रजिस्टर करें",
    updates: "अपडेट्स",
    marquee: "अभियान से जुड़ें: स्वावलंबी भारत युवा फेलोशिप बैच 2026 के लिए पंजीकरण वर्तमान में सक्रिय है। [संपर्क: 9685322910]"
  },
  footer: {
    title: "स्वावलंबी भारत अभियान",
    province: "छत्तीसगढ़ प्रांत",
    desc: "हर घर स्वदेशी हर युवा उद्यमी. हमारा लक्ष्य 2030 तक प्रत्येक नागरिक को रोजगार प्रदान करना और भारत को आत्मनिर्भर बनाना है। [cite: 184]",
    linksTitle: "महत्वपूर्ण लिंक्स",
    aboutMySba: "MySBA के बारे में",
    fellowshipDetails: "फेलोशिप विवरण",
    successStories: "सफलता की कहानियां",
    resourceMapping: "संसाधन मानचित्रण",
    jskCenters: "JSK केंद्र",
    resourcesTitle: "संसाधन (Resources)",
    msmeSchemes: "MSME योजनाएं",
    startupIndia: "स्टार्टअप इंडिया",
    skillIndia: "स्किल इंडिया",
    mudraLoan: "मुद्रा लोन जानकारी",
    regGuide: "पंजीकरण गाइड",
    contactTitle: "संपर्क करें",
    callWhatsapp: "कॉल/व्हाट्सएप",
    emailAddr: "ईमेल पता",
    location: "स्थान",
    rights: "स्वावलंबी भारत अभियान (SBA) - सर्वाधिकार सुरक्षित",
    privacy: "गोपनीयता नीति",
    terms: "सेवा की शर्तें",
    sitemap: "साइटमैप",
    atmanirbhar: "आत्मनिर्भर भारत"
  },
  homeNew: {
    badge: "स्वावलंबी भारत अभियान (SBA)",
    titlePart1: "स्वावलंबी भारत",
    titlePart2: "युवा फेलोशिप",
    subtitle: "यह नौकरी नहीं, राष्ट्र निर्माण और उद्यमिता सीखने की 6 माह की युवा फेलोशिप है। [cite: 181]",
    durationLabel: "अवधि (Duration)",
    durationVal: "6 महीने [cite: 41]",
    natureLabel: "प्रकृति (Nature)",
    natureVal: "पार्ट-टाइम [cite: 28]",
    engageLabel: "प्रतिबद्धता",
    engageVal: "6-8 घंटे/सप्ताह [cite: 45]",
    registerBtn: "अभी रजिस्टर करें",
    downloadBtn: "प्रस्ताव डाउनलोड करें",
    visionTitle: "हमारा विजन 2030 [cite: 5]",
    vision1: "उद्यमिता के प्रति मानसिकता में बदलाव [cite: 178]",
    vision2: "स्थानीय रोजगार के अवसर [cite: 18]",
    vision3: "ग्रामीण क्षेत्रों में संसाधन मानचित्रण [cite: 60]",
    vision4: "MSME योजनाओं के बारे में सरल जागरूकता [cite: 62]",
    rolesTitle: "भूमिकाएं और औसत परिणाम [cite: 81]",
    rolesSubtitle: "प्रत्येक फेलो को विशिष्ट मासिक वितरण के साथ एक स्पष्ट वर्टिकल सौंपा जाता है।",
    rolesAnalysis: "वर्टिकल विश्लेषण: 06 प्रमुख क्षेत्र",
    role1T: "स्थानीय मानचित्रण", role1D: "पारंपरिक कौशल और क्षेत्रीय व्यापार क्षमता की पहचान[cite: 95].",
    role2T: "सफलता की कहानियां", role2D: "स्थानीय उद्यमियों और स्टार्टअप्स की कहानियों का दस्तावेजीकरण[cite: 57].",
    role3T: "योजना विश्लेषण", role3D: "MSME, स्टार्टअप और कौशल योजनाओं की सरल प्रस्तुति[cite: 91].",
    role4T: "सोशल मीडिया", role4D: "प्लेटफॉर्म, पोस्ट, रील और इवेंट अभियानों का प्रबंधन[cite: 84].",
    role5T: "नवाचार आउटरीच", role5D: "कॉलेज परिसरों के भीतर विचारों और स्टार्टअप्स की पहचान करना[cite: 87].",
    role6T: "क्षेत्र समन्वय", role6D: "संस्थानों, व्यापारियों और छात्रों के साथ समन्वय करना[cite: 93].",
    hybridTitlePart1: "हाइब्रिड फेलोशिप",
    hybridTitlePart2: "मॉडल संरचना [cite: 118]",
    hybridDesc: "कम बजट वाले उच्च-प्रतिबद्धता प्रभाव के लिए डिज़ाइन किया गया, जिसमें स्वयंसेवा और मुख्य नेतृत्व पर ध्यान केंद्रित किया गया है।",
    volFellows: "स्वयंसेवक फेलो (Volunteer Fellows) (80%) [cite: 120]",
    volDesc: "बिना वजीफे के सीखने के परिणामों, क्षेत्र के अनुभव और मान्यता पर ध्यान दें[cite: 129, 130].",
    coreFellows: "मुख्य फेलो (Core Fellows) (20%) [cite: 124]",
    coreDesc: "2 महीने के प्रदर्शन के आधार पर चयनित। यात्रा भत्ते (₹2000-₹5000) के लिए पात्र[cite: 131].",
    coreCriteria: "मुख्य फेलो चयन मानदंड [cite: 133]",
    coreC1: "नियमित उपस्थिति और समय की पाबंदी [cite: 144]",
    coreC2: "अनुसंधान और दस्तावेजीकरण की गुणवत्ता [cite: 145]",
    coreC3: "सौंपे गए कार्यों को समय पर जमा करना [cite: 148]",
    coreC4: "पहल और नेतृत्व कौशल [cite: 147]",
    planTitle: "विस्तृत कार्य योजना (चरण-दर-चरण) [cite: 96]",
    planSubtitle: "मासिक आउटपुट-आधारित रिपोर्टिंग",
    planM1: "महीना 1 [cite: 100]", planT1: "उन्मुखीकरण और प्रशिक्षण [cite: 106]", planD1: "कार्यक्रम प्रेरण और उपकरण प्रशिक्षण।",
    planM2: "महीना 2 [cite: 101]", planT2: "स्थानीय मानचित्रण [cite: 109]", planD2: "क्षेत्रीय व्यापार अवसरों की पहचान।",
    planM3: "महीना 3 [cite: 102]", planT3: "सफलता की कहानियां [cite: 110]", planD3: "स्थानीय उद्यमियों का दस्तावेजीकरण।",
    planM4: "महीना 4 [cite: 103]", planT4: "सरकारी योजना अनुसंधान [cite: 111]", planD4: "MSME और स्टार्टअप कार्यक्रमों का विश्लेषण।",
    planM5: "महीना 5 [cite: 104]", planT5: "युवा आउटरीच [cite: 113]", planD5: "परिसर की भागीदारी और विचार सोर्सिंग।",
    planM6: "महीना 6 [cite: 105]", planT6: "अंतिम प्रस्तुति [cite: 115]", planD6: "रिपोर्ट जमा करना और राज्य सम्मान।",
    eligibilityTitle: "पात्रता मानदंड [cite: 66]",
    e1: "स्नातक / स्नातकोत्तर [cite: 68]",
    e2: "वर्तमान विश्वविद्यालय के छात्र [cite: 68]",
    e3: "कंप्यूटर और सोशल मीडिया ज्ञान [cite: 69]",
    e4: "राष्ट्र निर्माण में रुचि [cite: 74]",
    e5: "NSS / NCC / ई-सेल पृष्ठभूमि [cite: 75]",
    e6: "क्षेत्र कार्य और दस्तावेजीकरण में रुचि [cite: 76]",
    rewardsTitle: "मान्यता और पुरस्कार [cite: 156]",
    r1L: "प्रमाणन और एलओआर [cite: 163]", r1D: "राज्य स्तरीय सम्मान और मान्यता पत्र।",
    r2L: "महीने का सर्वश्रेष्ठ फेलो [cite: 161]", r2D: "विभिन्न वर्टिकल में शीर्ष प्रदर्शन के लिए मासिक पुरस्कार।",
    r3L: "प्रोजेक्ट क्रेडिट सपोर्ट [cite: 165]", r3D: "विश्वविद्यालय के पाठ्यक्रमों (NSS/NCC) के लिए फील्ड वर्क क्रेडिट।",
    ctaTitle1: "चलो मिलकर बनाएं",
    ctaTitle2: "स्वावलंबी छत्तीसगढ़, स्वावलंबी भारत! [cite: 128]",
    ctaSubtitle: "हर घर स्वदेशी हर युवा उद्यमी [cite: 128]",
    connectUs: "हमसे जुड़ें [cite: 182]",
    applyBtn: "फेलोशिप के लिए आवेदन करें",
    reportBtn: "रिपोर्ट पोर्टल",
    jskBtn: "JSK केंद्र"
  },
  about: {
    badge: "आत्मनिर्भर भारत 2030",
    titlePart1: "हमारा लक्ष्य:",
    titlePart2: "स्वावलंबी और समर्थ भारत",
    desc: "स्वावलंबी भारत अभियान (SBA) एक राष्ट्रीय पहल है जो 2030 तक भारत के हर नागरिक को रोजगार और स्वरोजगार के अवसर प्रदान करने के लिए प्रतिबद्ध है।",
    f1T: "मानसिकता परिवर्तन (Mindset Change)", f1D: "युवाओं की मानसिकता को नौकरी चाहने वाले से नौकरी देने वाले (उद्यमी) के रूप में बदलना।",
    f2T: "स्थानीय प्रोत्साहन (Local Promotion)", f2D: "स्थानीय स्तर पर रोजगारोन्मुखी उद्यमों और परियोजनाओं को प्रोत्साहित और समन्वित करना।",
    f3T: "एकीकृत केंद्र (Integrated Centers)", f3D: "प्रत्येक जिले में सभी संबंधित गतिविधियों के लिए एकीकृत रोजगार केंद्रों (JSK) की स्थापना।",
    digiTitle1: "MySBA:",
    digiTitle2: "डिजिटल प्लेटफॉर्म की शक्ति",
    digiDesc: "MySBA स्वावलंबी भारत अभियान का डिजिटल प्लेटफॉर्म है, जिसका उद्देश्य युवाओं की मानसिकता को बदलना और उन्हें सकारात्मक बदलाव लाने के लिए सशक्त बनाना है।",
    p1: "व्यक्तियों, उद्योगों और पेशेवरों को एक एकल मंच पर लाना।",
    p2: "स्थानीय स्तर पर युवाओं को सशक्त बनाने के लिए विकेंद्रीकृत दृष्टिकोण।",
    p3: "FPO, SHG और अन्य सहकारी आंदोलनों के विकास का समर्थन करना।",
    infraTitle: "डिजिटल इंफ्रास्ट्रक्चर",
    infraPT1: "भौतिक संपर्क बिंदु (Physical Touchpoint)",
    infraPT2: "जिला स्वावलंबन केंद्र (JSK)",
    infraPT3: "एक भौतिक बिंदु जहाँ युवा अपने भविष्य के निर्माण में सहायता और मार्गदर्शन प्राप्त कर सकते हैं।",
    infraES1: "आर्थिक सहायता (Economic Support)",
    infraES2: "कौशल दस्तावेजीकरण (Skill Documentation)",
    infraES3: "जमीनी स्तर पर स्थापित या प्रक्रियाधीन कौशल का आयोजन करके उद्यमिता को प्रोत्साहित करना।",
    cgTitle: "छत्तीसगढ़ प्रांत: स्थानीय अर्थव्यवस्था को गति",
    cgDesc: "छत्तीसगढ़ की स्थानीय अर्थव्यवस्था को मजबूत बनाने के लिए हम स्वरोजगार, नवाचार और उद्यमिता के माध्यम से युवाओं को राष्ट्र निर्माण से जोड़ रहे हैं। [cite: 53, 64]",
    pgLabel: "प्राथमिक लक्ष्य (Primary Goal)", pgDesc: "स्थानीय संसाधनों का मानचित्रण (Resource Mapping) [cite: 60]",
    sgLabel: "द्वितीयक लक्ष्य (Secondary Goal)", sgDesc: "सफलता की कहानियों का दस्तावेजीकरण [cite: 56, 57]",
    joinBtn: "हमारे साथ जुड़ें (Join the Movement)",
    contactTitle: "संपर्क विवरण (SBA Chhattisgarh)",
    whatsapp: "व्हाट्सएप: 9685322910 [cite: 183]",
    email: "ईमेल: sbachhattisgarh@gmail.com [cite: 183]",
    footer: "आत्मनिर्भर छत्तीसगढ़ | आत्मनिर्भर भारत"
  },
  fellowship: {
    badge: "संरचित 6-महीने का कार्यक्रम",
    titlePart1: "स्वावलंबी भारत",
    titlePart2: "युवा फेलोशिप",
    desc: "युवाओं, स्थानीय अवसरों और उद्यमिता मार्गदर्शन के बीच की खाई को पाटने की एक परिवर्तनकारी पहल। यह नौकरी नहीं है, बल्कि राष्ट्र निर्माण का एक मिशन है[cite: 18, 181]。",
    hybridTitle1: "हाइब्रिड फेलोशिप",
    hybridTitle2: "मॉडल",
    hybridDesc: "नेतृत्व और स्वयंसेवा पर ध्यान देने के साथ अधिकतम स्थानीय प्रभाव के लिए डिज़ाइन किया गया[cite: 118, 119]。",
    volTitle: "स्वयंसेवक फेलो (Volunteer Fellows) (80%)",
    volDesc: "प्रशिक्षण, क्षेत्र के जोखिम और सामाजिक प्रभाव पर ध्यान दें[cite: 120, 129]。",
    coreTitle: "मुख्य फेलो (Core Fellows) (20%)",
    coreDesc: "नेतृत्व भूमिकाओं के लिए 2 महीने के प्रदर्शन के आधार पर चयनित[cite: 124, 131]。",
    c1T: "समय प्रतिबद्धता", c1V: "6-8 घंटे/सप्ताह", c1D: "छात्रों और पेशेवरों के लिए लचीली भागीदारी[cite: 45]。",
    c2T: "प्रदर्शन समीक्षा", c2V: "2 महीने पर", c2D: "कोर फेलो ट्रैक के लिए कठोर चयन[cite: 134, 142]。",
    c3T: "वित्तीय सहायता", c3V: "₹2000 - ₹5000", c3D: "चयनित कोर फेलो के लिए सहायता/यात्रा भत्ता[cite: 131]。",
    c4T: "मान्यता", c4V: "राष्ट्रीय स्तर", c4D: "प्रमाणपत्र, LOR और सर्वश्रेष्ठ फेलो पुरस्कार[cite: 49, 163]。",
    rolesTitle: "भूमिकाएं और औसत परिणाम",
    role1T: "संसाधन मानचित्रण", role1D: "पारंपरिक कौशल और व्यापार क्षमता की पहचान[cite: 94, 177]。",
    role2T: "सफलता की कहानियां", role2D: "स्थानीय उद्यमियों और व्यवसायों की कहानियों का दस्तावेजीकरण[cite: 56, 57]。",
    role3T: "योजना विश्लेषण", role3D: "MSME और स्टार्टअप योजनाओं की सरल प्रस्तुति[cite: 90, 91]。",
    role4T: "सोशल मीडिया", role4D: "प्लेटफॉर्म प्रबंधन और सामग्री अभियान[cite: 82, 84]。",
    role5T: "नवाचार आउटरीच", role5D: "कॉलेजों में विचारों और स्टार्टअप्स की पहचान करना[cite: 86, 87]。",
    role6T: "क्षेत्र समन्वय", role6D: "संस्थानों और उद्यमियों के साथ समन्वय[cite: 92, 93]。",
    roadmapTitle: "कार्यान्वयन रोडमैप",
    planM1: "महीना 1", planT1: "उन्मुखीकरण और प्रशिक्षण", planD1: "SBA टूल और शोध विधियों में प्रेरण[cite: 106, 108]。",
    planM2: "महीना 2", planT2: "स्थानीय मानचित्रण", planD2: "क्षेत्रीय संसाधनों और व्यवसायों का डेटा संग्रह[cite: 107, 109]。",
    planM3: "महीना 3", planT3: "सफलता की कहानियां", planD3: "दस्तावेज़ीकरण और डिजिटल कहानी निर्माण[cite: 110]。",
    planM4: "महीना 4", planT4: "योजना अनुसंधान", planD4: "MSME और ऋण कार्यक्रमों का गहन विश्लेषण[cite: 111, 112]。",
    planM5: "महीना 5", planT5: "परिसर आउटरीच", planD5: "कॉलेजों में उद्यमिता जागरूकता[cite: 113]。",
    planM6: "महीना 6", planT6: "अंतिम रिपोर्ट", planD6: "अंतिम प्रस्तुति और प्रभाव प्रस्तुत करना[cite: 114, 115]。",
    whoTitle: "कौन जुड़ सकता है?",
    e1: "स्नातक / पीजी छात्र", e2: "कंप्यूटर ज्ञान", e3: "राष्ट्र निर्माण में रुचि", e4: "NSS / NCC / ई-सेल पृष्ठभूमि",
    applyBtn: "अभी आवेदन करें",
    batchText: "बैच 2026 पंजीकरण खुला"
  }
`;

content = content.replace(/\\s*nav:\\s*\\{[\\s\\S]*?\\},/g, '');
content = content.replace(
  /export const en = \{/,
  "export const en = {" + enAdditions + ","
);

content = content.replace(
  /export const hi: Dictionary = \{/,
  "export const hi: Dictionary = {" + hiAdditions + ","
);

fs.writeFileSync(dictPath, content);
console.log("Dictionaries updated successfully");
